sudo: required
services:
  - docker
language: go
go:
  - "1.12.x"
env:
  - GO111MODULE=on make build

install:
  - go mod download

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - echo $GO_FILES | xargs gofmt -l                    # Fail if a .go file hasn't been formatted with gofmt
  - go test -v -race ./...                             # Run all the tests with the race detector enabled
  - go vet ./...                                       # go vet is the official Go static analyzer
  - staticcheck ./...                                  # "go vet on steroids" + linter

before_deploy:
  - make agent-docker

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
