[[constraint]]
  name = "k8s.io/cli-runtime"
  source = "github.com/kubernetes/cli-runtime"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v17.03.2-ce"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
